### ISSUE TITLE
version 2.0

### ISSUE THREAD

**Issue by SpellsingerX** [npetrovski/l2js-client#52]
The new version 2.0
I have some doubts

How do I get the logs as in version 1.x
using 

`process.env.L2JSC_LOG_LEVEL = '8';`

When I try to enter the game I get an Undefined

```
[30/12/2021 01:22:50] INFO MMOConnection Connected ['149.56.28.81:2106']
Undefined
```

This log is useful for creating new packages.

My second doubt, in version 1.x I get the opecode is I call the class,
In this version 2.0 I don't need to pass the opencode? just do the json in the package format?

Last doubt, is there an automatic generator that generates the game packages?

Thanks

**Comment by w3nder** [comment]
> The new version 2.0 I have some doubts
> 
> How do I get the logs as in version 1.x using
> 
> `process.env.L2JSC_LOG_LEVEL = '8';`
> 
> When I try to enter the game I get an Undefined
> 
> ```
> [30/12/2021 01:22:50] INFO MMOConnection Connected ['149.56.28.81:2106']
> Undefined
> ```
> 
> This log is useful for creating new packages.
> 
> My second doubt, in version 1.x I get the opecode is I call the class, In this version 2.0 I don't need to pass the opencode? just do the json in the package format?
> 
> Last doubt, is there an automatic generator that generates the game packages?
> 
> Thanks

![image](https://user-images.githubusercontent.com/1123103/154143463-cac98cde-39ba-4281-b7ec-60142c60129a.png)


to display the log you have to set an environment variable with the name l2jsc_log_level
with the value of the type of log you want.

this print is the result of the connection with the lineage2toggle

but i was not successful in sending the package.
0x32 RequestLogin


because its a beta version, problems can happen.

i will study the 2.0 beta version to try to contribute.

**Comment by unk0x** [comment]
> Last doubt, is there an automatic generator that generates the game packages?
> 
> Thanks

I'm creating a small script [Converte Packet ](https://github.com/unk0x/l2ph-packet-json) that reading the ini files from l2phx is converting to json.
Still some things missing, like enabling the same json or json from version 2.0 format
For those who have difficulty creating new packages, I believe this script will help
